name: Generate API docs JSON

on:
  push:
  release:
    types: [published]

jobs:
  build-api-doc:
    runs-on: ubuntu-latest
    name: "Generate API docs JSON"
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: v3.8.5

    - name: Download external libraries
      run: |
        EXT_VERSION=`node ./.github/workflows/get-native-external-version.js`
        git clone --branch $EXT_VERSION --depth 1 https://github.com/cocos/cocos-engine-external native/external

    - name: Install
      run: |
        npm i

    - name: Checkout the tool
      uses: actions/checkout@v4
      with:
        repository: dumganhar/creator-api-doc
        path: creator-api-doc
        ref: main

    - name: Generate
      run: |
        pwd
        ls -l
        ENGINE_ROOT=$(pwd)
        echo "ENGINE_ROOT: ${ENGINE_ROOT}"
        cd creator-api-doc
        npm i
        npm run build
        npm run test
        node ./lib/cli.js -p $ENGINE_ROOT -o $ENGINE_ROOT/Cocos-Creator-API.json
        ls -l


    # - name: Pack dist files
    #   if: github.event_name == 'release'
    #   uses: thedoctor0/zip-release@main
    #   with:
    #     type: 'zip'
    #     directory: 'build/swig-linux'
    #     path: '.'
    #     filename: 'swig-linux.zip'
    #     exclusions: '*/csharp/* */d/* */go/* */guile/* */java/* */javascript/jsc/* */javascript/v8/* */lua/* */mzscheme/* */ocaml/* */octave/* */perl5/* */php/* */python/* */r/* */ruby/* */scilab/* */tcl/* */xml/*'

    # - name: Upload to Release
    #   if: github.event_name == 'release'
    #   uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: build/swig-linux/swig-linux.zip
    #     asset_name: swig-linux.zip
    #     tag: ${{ github.ref }}
  


