name: Generate API docs JSON

on:
  push:
    tags:
      - '**'
    branches-ignore:
      - '**'
  pull_request:
  workflow_dispatch:
    inputs:
      target_tag:
        description: 'The ref (branch or tag) to build API docs'
        type: string
        default: '3.8.3'
        required: true

jobs:
  build-api-doc:
    runs-on: ubuntu-latest
    name: "Generate API docs JSON"
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Get ref
      id: step-id-get-ref
      run: |
        if [ "${{ github.event_name }}" = 'workflow_dispatch' ]; then
          echo "Get ref from workflow_dispatch"
          echo "ENGINE_REF=${{ github.event.inputs.target_tag }}" >> $GITHUB_OUTPUT
        else
          echo "Get ref from push"
          echo "ENGINE_REF=${{ github.ref }}" >> $GITHUB_OUTPUT
        fi

    - name: Show ref
      run: |
        echo "ref: ${{ steps.step-id-get-ref.outputs.ENGINE_REF }}"

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.step-id-get-ref.outputs.ENGINE_REF }}

    - name: Checkout the tool
      uses: actions/checkout@v4
      with:
        repository: cocos/creator-api-doc
        path: creator-api-doc
        ref: main

    - name: Install the tool
      run: |
        cd creator-api-doc
        npm i
        # apply the url patch for typedoc@0.22.13
        npm run apply-patch
        npm run build

    - name: Patch taobao npm mirror 1
      if: github.event_name == 'workflow_dispatch'
      run: |
        set +e
        ENGINE_ROOT=$(pwd)
        cd creator-api-doc/scripts
        ./version_compare.sh ${{ steps.step-id-get-ref.outputs.ENGINE_REF }}
        exit_status=$?
        set -e

        if [ $exit_status -eq 0 ]; then
            echo "version_compare.sh succeed"
        else
            echo "version_compare.sh failed $exit_status"
            node ./replace-taobao.js $ENGINE_ROOT
        fi

    - name: Patch taobao npm mirror 2
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "replace 2..."

    - name: Download external libraries
      run: |
        EXT_VERSION=`grep checkout native/external-config.json | awk -F'"' '{print $4}'`
        echo "EXT_VERSION: ${EXT_VERSION}"
        git clone --branch $EXT_VERSION --depth 1 https://github.com/cocos/cocos-engine-external native/external

    - name: Install Cocos Engine
      run: |
        npm i

    - name: Generate
      run: |
        pwd
        ls -l
        ENGINE_ROOT=$(pwd)
        echo "ENGINE_ROOT: ${ENGINE_ROOT}"
        cd creator-api-doc
        node ./lib/cli.js -p $ENGINE_ROOT -o $ENGINE_ROOT/Cocos-Creator-API.json
        ls -l ..

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with: 
        name: Cocos-Creator-API
        path: Cocos-Creator-API.json

